package si.uni_lj.fri.pbd.miniapp3.models

import si.uni_lj.fri.pbd.miniapp3.database.entity.RecipeDetails
import si.uni_lj.fri.pbd.miniapp3.models.dto.RecipeDetailsDTO
import si.uni_lj.fri.pbd.miniapp3.models.dto.RecipeSummaryDTO

object Mapper {

    fun mapRecipeDetailsToRecipeSummaryIm(rec: RecipeDetails): RecipeSummaryIM {
        return RecipeSummaryIM(rec.strMeal!!, rec.strMealThumb!!, rec.idMeal!!)
    }
    // TODO: Uncomment the code below

    fun mapRecipeDetailsDtoToRecipeDetails(isFavorite: Boolean?, dto: RecipeDetailsDTO): RecipeDetails {
        return RecipeDetails(
            isFavorite = isFavorite,
            idMeal = dto.idMeal,
            strMeal = dto.strMeal,
            strCategory = dto.strCategory,
            strArea = dto.strArea,
            strInstructions = dto.strInstructions,
            strMealThumb = dto.strMealThumb,
            strYoutube = dto.strYoutube,
            strIngredient1 = dto.strIngredient1,
            strIngredient2 = dto.strIngredient2,
            strIngredient3 = dto.strIngredient3,
            strIngredient4 = dto.strIngredient4,
            strIngredient5 = dto.strIngredient5,
            strIngredient6 = dto.strIngredient6,
            strIngredient7 = dto.strIngredient7,
            strIngredient8 = dto.strIngredient8,
            strIngredient9 = dto.strIngredient9,
            strIngredient10 = dto.strIngredient10,
            strIngredient11 = dto.strIngredient11,
            strIngredient12 = dto.strIngredient12,
            strIngredient13 = dto.strIngredient13,
            strIngredient14 = dto.strIngredient14,
            strIngredient15 = dto.strIngredient15,
            strIngredient16 = dto.strIngredient16,
            strIngredient17 = dto.strIngredient17,
            strIngredient18 = dto.strIngredient18,
            strIngredient19 = dto.strIngredient19,
            strIngredient20 = dto.strIngredient20,
            strMeasure1 = dto.strMeasure1,
            strMeasure2 = dto.strMeasure2,
            strMeasure3 = dto.strMeasure3,
            strMeasure4 = dto.strMeasure4,
            strMeasure5 = dto.strMeasure5,
            strMeasure6 = dto.strMeasure6,
            strMeasure7 = dto.strMeasure7,
            strMeasure8 = dto.strMeasure8,
            strMeasure9 = dto.strMeasure9,
            strMeasure10 = dto.strMeasure10,
            strMeasure11 = dto.strMeasure11,
            strMeasure12 = dto.strMeasure12,
            strMeasure13 = dto.strMeasure13,
            strMeasure14 = dto.strMeasure14,
            strMeasure15 = dto.strMeasure15,
            strMeasure16 = dto.strMeasure16,
            strMeasure17 = dto.strMeasure17,
            strMeasure18 = dto.strMeasure18,
            strMeasure19 = dto.strMeasure19,
            strMeasure20 = dto.strMeasure20,
            strSource = dto.strSource
        )
    }

    fun mapRecipeDetailsDtoToRecipeDetailsIm(isFavorite: Boolean?, dto: RecipeDetailsDTO): RecipeDetailsIM {
        return RecipeDetailsIM(
            isFavorite = isFavorite,
            idMeal = dto.idMeal,
            strMeal = dto.strMeal,
            strCategory = dto.strCategory,
            strArea = dto.strArea,
            strInstructions = dto.strInstructions,
            strMealThumb = dto.strMealThumb,
            strYoutube = dto.strYoutube,
            strIngredient1 = dto.strIngredient1,
            strIngredient2 = dto.strIngredient2,
            strIngredient3 = dto.strIngredient3,
            strIngredient4 = dto.strIngredient4,
            strIngredient5 = dto.strIngredient5,
            strIngredient6 = dto.strIngredient6,
            strIngredient7 = dto.strIngredient7,
            strIngredient8 = dto.strIngredient8,
            strIngredient9 = dto.strIngredient9,
            strIngredient10 = dto.strIngredient10,
            strIngredient11 = dto.strIngredient11,
            strIngredient12 = dto.strIngredient12,
            strIngredient13 = dto.strIngredient13,
            strIngredient14 = dto.strIngredient14,
            strIngredient15 = dto.strIngredient15,
            strIngredient16 = dto.strIngredient16,
            strIngredient17 = dto.strIngredient17,
            strIngredient18 = dto.strIngredient18,
            strIngredient19 = dto.strIngredient19,
            strIngredient20 = dto.strIngredient20,
            strMeasure1 = dto.strMeasure1,
            strMeasure2 = dto.strMeasure2,
            strMeasure3 = dto.strMeasure3,
            strMeasure4 = dto.strMeasure4,
            strMeasure5 = dto.strMeasure5,
            strMeasure6 = dto.strMeasure6,
            strMeasure7 = dto.strMeasure7,
            strMeasure8 = dto.strMeasure8,
            strMeasure9 = dto.strMeasure9,
            strMeasure10 = dto.strMeasure10,
            strMeasure11 = dto.strMeasure11,
            strMeasure12 = dto.strMeasure12,
            strMeasure13 = dto.strMeasure13,
            strMeasure14 = dto.strMeasure14,
            strMeasure15 = dto.strMeasure15,
            strMeasure16 = dto.strMeasure16,
            strMeasure17 = dto.strMeasure17,
            strMeasure18 = dto.strMeasure18,
            strMeasure19 = dto.strMeasure19,
            strMeasure20 = dto.strMeasure20,
            strSource = dto.strSource
        )
    }

    fun mapRecipeDetailsToRecipeDetailsIm(isFavorite: Boolean?, dto: RecipeDetails): RecipeDetailsIM {
        return RecipeDetailsIM(
            isFavorite = isFavorite,
            idMeal = dto.idMeal,
            strMeal = dto.strMeal,
            strCategory = dto.strCategory,
            strArea = dto.strArea,
            strInstructions = dto.strInstructions,
            strMealThumb = dto.strMealThumb,
            strYoutube = dto.strYoutube,
            strIngredient1 = dto.strIngredient1,
            strIngredient2 = dto.strIngredient2,
            strIngredient3 = dto.strIngredient3,
            strIngredient4 = dto.strIngredient4,
            strIngredient5 = dto.strIngredient5,
            strIngredient6 = dto.strIngredient6,
            strIngredient7 = dto.strIngredient7,
            strIngredient8 = dto.strIngredient8,
            strIngredient9 = dto.strIngredient9,
            strIngredient10 = dto.strIngredient10,
            strIngredient11 = dto.strIngredient11,
            strIngredient12 = dto.strIngredient12,
            strIngredient13 = dto.strIngredient13,
            strIngredient14 = dto.strIngredient14,
            strIngredient15 = dto.strIngredient15,
            strIngredient16 = dto.strIngredient16,
            strIngredient17 = dto.strIngredient17,
            strIngredient18 = dto.strIngredient18,
            strIngredient19 = dto.strIngredient19,
            strIngredient20 = dto.strIngredient20,
            strMeasure1 = dto.strMeasure1,
            strMeasure2 = dto.strMeasure2,
            strMeasure3 = dto.strMeasure3,
            strMeasure4 = dto.strMeasure4,
            strMeasure5 = dto.strMeasure5,
            strMeasure6 = dto.strMeasure6,
            strMeasure7 = dto.strMeasure7,
            strMeasure8 = dto.strMeasure8,
            strMeasure9 = dto.strMeasure9,
            strMeasure10 = dto.strMeasure10,
            strMeasure11 = dto.strMeasure11,
            strMeasure12 = dto.strMeasure12,
            strMeasure13 = dto.strMeasure13,
            strMeasure14 = dto.strMeasure14,
            strMeasure15 = dto.strMeasure15,
            strMeasure16 = dto.strMeasure16,
            strMeasure17 = dto.strMeasure17,
            strMeasure18 = dto.strMeasure18,
            strMeasure19 = dto.strMeasure19,
            strMeasure20 = dto.strMeasure20,
            strSource = dto.strSource
        )
    }

    fun mapRecipeDetailsToRecipeDetailsDTO(dto: RecipeDetails): RecipeSummaryDTO {
        return RecipeSummaryDTO(
            strMeal = dto.strMeal,
            strMealThumb = dto.strMealThumb,
            idMeal = dto.idMeal
        )
    }

    fun IMtoDto(recipeIM: RecipeDetailsIM): RecipeDetailsDTO {
        return RecipeDetailsDTO(
            idMeal = recipeIM.idMeal,
            strMeal = recipeIM.strMeal,
            strCategory = recipeIM.strCategory,
            strArea = recipeIM.strArea,
            strInstructions = recipeIM.strInstructions,
            strMealThumb = recipeIM.strMealThumb,
            strYoutube = recipeIM.strYoutube,
            strIngredient1 = recipeIM.strIngredient1,
            strIngredient2 = recipeIM.strIngredient2,
            strIngredient3 = recipeIM.strIngredient3,
            strIngredient4 = recipeIM.strIngredient4,
            strIngredient5 = recipeIM.strIngredient5,
            strIngredient6 = recipeIM.strIngredient6,
            strIngredient7 = recipeIM.strIngredient7,
            strIngredient8 = recipeIM.strIngredient8,
            strIngredient9 = recipeIM.strIngredient9,
            strIngredient10 = recipeIM.strIngredient10,
            strIngredient11 = recipeIM.strIngredient11,
            strIngredient12 = recipeIM.strIngredient12,
            strIngredient13 = recipeIM.strIngredient13,
            strIngredient14 = recipeIM.strIngredient14,
            strIngredient15 = recipeIM.strIngredient15,
            strIngredient16 = recipeIM.strIngredient16,
            strIngredient17 = recipeIM.strIngredient17,
            strIngredient18 = recipeIM.strIngredient18,
            strIngredient19 = recipeIM.strIngredient19,
            strIngredient20 = recipeIM.strIngredient20,
            strMeasure1 = recipeIM.strMeasure1,
            strMeasure2 = recipeIM.strMeasure2,
            strMeasure3 = recipeIM.strMeasure3,
            strMeasure4 = recipeIM.strMeasure4,
            strMeasure5 = recipeIM.strMeasure5,
            strMeasure6 = recipeIM.strMeasure6,
            strMeasure7 = recipeIM.strMeasure7,
            strMeasure8 = recipeIM.strMeasure8,
            strMeasure9 = recipeIM.strMeasure9,
            strMeasure10 = recipeIM.strMeasure10,
            strMeasure11 = recipeIM.strMeasure11,
            strMeasure12 = recipeIM.strMeasure12,
            strMeasure13 = recipeIM.strMeasure13,
            strMeasure14 = recipeIM.strMeasure14,
            strMeasure15 = recipeIM.strMeasure15,
            strMeasure16 = recipeIM.strMeasure16,
            strMeasure17 = recipeIM.strMeasure17,
            strMeasure18 = recipeIM.strMeasure18,
            strMeasure19 = recipeIM.strMeasure19,
            strMeasure20 = recipeIM.strMeasure20,
            strSource = recipeIM.strSource
        )
    }
}
